name: Create release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1

      - name: Install pyinstaller
        run: python -m pip install pyinstaller

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller "win-wallpaper.py" --onefile

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: dist/win-wallpaper.exe
